function normalizeRole(value) {
  return typeof value === "string" ? value.trim().toLowerCase() : "";
}

function hasAllowedRole(user, allowedRoles) {
  const normalizedAllowedRoles = new Set((allowedRoles || []).map(normalizeRole).filter(Boolean));
  const userRole = normalizeRole(user?.role);

  if (userRole && normalizedAllowedRoles.has(userRole)) {
    return true;
  }

  // Fallback based on the token shape generated by this API:
  // SuperAdmin tokens have no clientId, client admin tokens always have one.
  if (normalizedAllowedRoles.has("superadmin") && user?.userId && user?.clientId == null) {
    return true;
  }

  if (normalizedAllowedRoles.has("admin") && user?.userId && user?.clientId) {
    return true;
  }

  return false;
}

function roleMiddleware(allowedRoles) {
  return (req, res, next) => {
    if (!req.user) {
      console.warn("[ROLE] Missing req.user", {
        path: req.originalUrl,
        method: req.method
      });
      return res.status(401).json({
        message: "Unauthorized"
      });
    }

    const allowed = hasAllowedRole(req.user, allowedRoles);

    if (!allowed) {
      console.warn("[ROLE] Forbidden", {
        path: req.originalUrl,
        method: req.method,
        allowedRoles,
        user: req.user
      });
      return res.status(403).json({
        message: "Forbidden"
      });
    }

    console.info("[ROLE] Allowed", {
      path: req.originalUrl,
      method: req.method,
      allowedRoles,
      user: req.user
    });
    next();
  };
}

module.exports = roleMiddleware;
